### ISSUE TITLE
эту модель можно расширить из готовой django.contrib.auth.models.User

### ISSUE THREAD

**Issue by mikhailborodin** [maryiaLichko/main#1]
https://github.com/maryiaLichko/main/blob/878ed0f76b5d733167f269a17da37a7aab766a57/main1/models.py#L5

https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#extending-the-existing-user-model

в этой модели должен быть признак капитан/обычный участник
и в ней же должна быть ссылка ForeignKey, так как участник может быть только в одной команде

**Comment by maryiaLichko** [comment]
class Users(models.Model):
    captain = models.CharField(max_length=20)
    user = models.CharField(max_length=20)
    team = models.ForeignKey(User, on_delete=models.CASCADE)

что-то такое?

**Comment by mikhailborodin** [comment]
class Profile(models.Model):
is_captain = models.BooleanField(default=False)
user = models.OneToOneField(User)
team = models.ForeignKey(Team, on_delete=models.CASCADE)

**Comment by maryiaLichko** [comment]
> class Profile(models.Model):
> is_captain = models.BooleanField(default=False)
> user = models.OneToOneField(User)
> team = models.ForeignKey(Team, on_delete=models.CASCADE)

please review
